export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'


export const USER_IMAGE_SUCCESS= 'USER_IMAGE_SUCCESS'
export const USER_IMAGE_FAIL = 'USER_IMAGE_FAIL'
